apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookstore.fullname" . }}-api
  labels:
    {{- include "bookstore.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bookstore.apiSelectorLabels" . | nindent 4 }}
